"""add_cardiac_fields

Revision ID: 6dd7f3136974
Revises: 0018
Create Date: 2026-06-01 23:10:01.504894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6dd7f3136974'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_cardiac', sa.Column('lvot_diameter', sa.Float(), nullable=True))
    op.add_column('patient_cardiac', sa.Column('lvot_vti', sa.Float(), nullable=True))
    op.add_column('patient_cardiac', sa.Column('heart_rate', sa.Integer(), nullable=True))
    op.add_column('patient_cardiac', sa.Column('stroke_volume', sa.Float(), nullable=True))
    op.add_column('patient_cardiac', sa.Column('cardiac_output', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_cardiac', 'cardiac_output')
    op.drop_column('patient_cardiac', 'stroke_volume')
    op.drop_column('patient_cardiac', 'heart_rate')
    op.drop_column('patient_cardiac', 'lvot_vti')
    op.drop_column('patient_cardiac', 'lvot_diameter')
    # ### end Alembic commands ###

