"""Add esa_modified_at to MonthlyRecord

Revision ID: d486bde0fe85
Revises: afd5590efe75
Create Date: 2026-06-11 07:01:53.490477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd486bde0fe85'
down_revision: Union[str, None] = 'afd5590efe75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_records', sa.Column('esa_modified_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_records', 'esa_modified_at')
    # ### end Alembic commands ###
