"""expand_pds_schema

Revision ID: e44246158d0d
Revises: 0017
Create Date: 2026-06-01 07:19:20.327500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e44246158d0d'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('patient_symptom_reports', sa.Column('dialysis_recovery_time', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_physical_exhaustion', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_lack_of_energy', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_sleepiness', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_reduced_stamina', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_prolonged_rest', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_washed_out', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('fatigue_motivation_loss', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_brain_fog', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_poor_concentration', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_slowed_thinking', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_memory_difficulty', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_reduced_alertness', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cog_decision_difficulty', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_low_mood', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_anxiety', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_irritability', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_emotional_exhaustion', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_overwhelmed', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('psych_reduced_purpose', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_muscle_weakness', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_dizziness', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_headache', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_body_pain', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_sob', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_palpitations', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_gait_instability', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('phys_cramps', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('sleep_daytime_sleepiness', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('sleep_poor_sleep_post_hd', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('sleep_unrefreshing', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('sleep_disturbance', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_mobility', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_household', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_work', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_social', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_exercise', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_family', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_independence', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('func_life_participation', sa.Integer(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('symptoms_worse_time', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('symptoms_compare_nondialysis', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('associated_contributors', sa.Text(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('activity_average_daily', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('activity_posthd_reduction', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('activity_exercise_tolerance', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('narrative_most_disabling', sa.Text(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('narrative_activities_affected', sa.Text(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('narrative_helps_recovery', sa.Text(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('narrative_makes_worse', sa.Text(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cgi_severity', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cgi_dominant_phenotype', sa.String(), nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('suggested_interventions', sa.Text(), nullable=True))
    
    op.drop_column('patient_symptom_reports', 'post_hd_mood')
    op.drop_column('patient_symptom_reports', 'missed_social_or_work_event')
    op.drop_column('patient_symptom_reports', 'dialysis_recovery_time_mins')
    op.drop_column('patient_symptom_reports', 'daily_activity_impact')
    op.drop_column('patient_symptom_reports', 'tiredness_score')
    op.drop_column('patient_symptom_reports', 'cognitive_alertness')
    op.drop_column('patient_symptom_reports', 'energy_level_score')
    op.drop_column('patient_symptom_reports', 'sleepiness_severity')


def downgrade() -> None:
    op.add_column('patient_symptom_reports', sa.Column('sleepiness_severity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('energy_level_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('cognitive_alertness', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('tiredness_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('daily_activity_impact', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('dialysis_recovery_time_mins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('missed_social_or_work_event', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patient_symptom_reports', sa.Column('post_hd_mood', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    op.drop_column('patient_symptom_reports', 'suggested_interventions')
    op.drop_column('patient_symptom_reports', 'cgi_dominant_phenotype')
    op.drop_column('patient_symptom_reports', 'cgi_severity')
    op.drop_column('patient_symptom_reports', 'narrative_makes_worse')
    op.drop_column('patient_symptom_reports', 'narrative_helps_recovery')
    op.drop_column('patient_symptom_reports', 'narrative_activities_affected')
    op.drop_column('patient_symptom_reports', 'narrative_most_disabling')
    op.drop_column('patient_symptom_reports', 'activity_exercise_tolerance')
    op.drop_column('patient_symptom_reports', 'activity_posthd_reduction')
    op.drop_column('patient_symptom_reports', 'activity_average_daily')
    op.drop_column('patient_symptom_reports', 'associated_contributors')
    op.drop_column('patient_symptom_reports', 'symptoms_compare_nondialysis')
    op.drop_column('patient_symptom_reports', 'symptoms_worse_time')
    op.drop_column('patient_symptom_reports', 'func_life_participation')
    op.drop_column('patient_symptom_reports', 'func_independence')
    op.drop_column('patient_symptom_reports', 'func_family')
    op.drop_column('patient_symptom_reports', 'func_exercise')
    op.drop_column('patient_symptom_reports', 'func_social')
    op.drop_column('patient_symptom_reports', 'func_work')
    op.drop_column('patient_symptom_reports', 'func_household')
    op.drop_column('patient_symptom_reports', 'func_mobility')
    op.drop_column('patient_symptom_reports', 'sleep_disturbance')
    op.drop_column('patient_symptom_reports', 'sleep_unrefreshing')
    op.drop_column('patient_symptom_reports', 'sleep_poor_sleep_post_hd')
    op.drop_column('patient_symptom_reports', 'sleep_daytime_sleepiness')
    op.drop_column('patient_symptom_reports', 'phys_cramps')
    op.drop_column('patient_symptom_reports', 'phys_gait_instability')
    op.drop_column('patient_symptom_reports', 'phys_palpitations')
    op.drop_column('patient_symptom_reports', 'phys_sob')
    op.drop_column('patient_symptom_reports', 'phys_body_pain')
    op.drop_column('patient_symptom_reports', 'phys_headache')
    op.drop_column('patient_symptom_reports', 'phys_dizziness')
    op.drop_column('patient_symptom_reports', 'phys_muscle_weakness')
    op.drop_column('patient_symptom_reports', 'psych_reduced_purpose')
    op.drop_column('patient_symptom_reports', 'psych_overwhelmed')
    op.drop_column('patient_symptom_reports', 'psych_emotional_exhaustion')
    op.drop_column('patient_symptom_reports', 'psych_irritability')
    op.drop_column('patient_symptom_reports', 'psych_anxiety')
    op.drop_column('patient_symptom_reports', 'psych_low_mood')
    op.drop_column('patient_symptom_reports', 'cog_decision_difficulty')
    op.drop_column('patient_symptom_reports', 'cog_reduced_alertness')
    op.drop_column('patient_symptom_reports', 'cog_memory_difficulty')
    op.drop_column('patient_symptom_reports', 'cog_slowed_thinking')
    op.drop_column('patient_symptom_reports', 'cog_poor_concentration')
    op.drop_column('patient_symptom_reports', 'cog_brain_fog')
    op.drop_column('patient_symptom_reports', 'fatigue_motivation_loss')
    op.drop_column('patient_symptom_reports', 'fatigue_washed_out')
    op.drop_column('patient_symptom_reports', 'fatigue_prolonged_rest')
    op.drop_column('patient_symptom_reports', 'fatigue_reduced_stamina')
    op.drop_column('patient_symptom_reports', 'fatigue_sleepiness')
    op.drop_column('patient_symptom_reports', 'fatigue_lack_of_energy')
    op.drop_column('patient_symptom_reports', 'fatigue_physical_exhaustion')
    op.drop_column('patient_symptom_reports', 'dialysis_recovery_time')
